ln -sf ~/dotfiles/nvim/init.vim ~/.config/nvim/init.vim
ln -sf ~/dotfiles/nvim/rc/dein.rc.vim ~/.config/nvim/rc/dein.rc.vim
ln -sf ~/dotfiles/nvim/rc/dein.toml ~/.config/nvim/rc/dein.toml
ln -sf ~/dotfiles/nvim/rc/dein_front.toml ~/.config/nvim/rc/dein_front.toml
ln -sf ~/dotfiles/nvim/rc/dein_lang.toml ~/.config/nvim/rc/dein_lang.toml
ln -sf ~/dotfiles/nvim/rc/dein_lazy.toml ~/.config/nvim/rc/dein_lazy.toml
ln -sf ~/dotfiles/nvim/rc/dein_neo.toml ~/.config/nvim/rc/dein_neo.toml
ln -sf ~/dotfiles/nvim/rc/dein_python.toml ~/.config/nvim/rc/dein_python.toml
ln -sf ~/dotfiles/nvim/rc/dein_ruby.toml ~/.config/nvim/rc/dein_ruby.toml
ln -sf ~/dotfiles/nvim/rc/dein_clang.toml ~/.config/nvim/rc/dein_clang.toml
ln -sf ~/dotfiles/nvim/rc/filetype.rc.vim ~/.config/nvim/rc/filetype.rc.vim
ln -sf ~/dotfiles/nvim/rc/options.rc.vim ~/.config/nvim/rc/options.rc.vim
ln -sf ~/dotfiles/nvim/rc/command.rc.vim ~/.config/nvim/rc/command.rc.vim
