#===================#
# Plugin for Plugin
#===================#
[[plugins]]
repo = 'Shougo/dein.vim'

#==========#
# FileType
#==========#
[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
	if !exists('g:context_filetype#filetypes')
		let g:context_filetype#filetypes = {}
	endif
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']

#[[plugins]]
#repo = 'Yggdroot/indentLine'
#hook_add = '''
#let g:indentLine_setColors = 0
#set list listchars=tab:\¦\ 
#'''

#
# PHP設定
[[plugins]]
repo = 'phpactor/phpactor'
no_ft = ['php']
build = 'composer install'

[[plugins]]
repo = 'jwalton512/vim-blade'

#=============================#
# ColorSchema - PowerlineShell( (hybird, hook)->lighttiger2505さん引用 )
#=============================#
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
set background=dark
'''

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'tomasr/molokai'


[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'michalbachowski/vim-wombat256mod'
#hook_add = '''
#au MyAutoCmd VimEnter * nested colorscheme wombat-256mod
#'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline_theme = 'badwolf'
let g:airline#extensions#virtualenv#enabled = 1
'''

#=============================#
# Git関連設定(lighttiger2505さん引用)
#=============================#
# nerdirtree表示
[[plugins]]
repo ='scrooloose/nerdtree'
hook_source = '''
let g:nerdtree_tabs_open_console_startup = 1
let NERDTreeShowHideen = 1
let NERDTreeMapOpenInTab='<Enter>'
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_source = '''
nnoremap <slient><C-n> :NERDTreeTabsToggle<CR>
'''


#[[plugins]]
#repo = 'tpope/vim-fugitive'
#hook_add = '''
#nnoremap <Leader>g [figitive]
#nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
#nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
#nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
#'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'airblade/vim-gitgutter'
